import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const git = spawnSync("git", ["rev-parse", "--git-path", "hooks"], { encoding: "utf8" });
if (git.status !== 0) {
  throw new Error(git.stderr || "Cannot locate Git hooks directory");
}

const hooksDirectory = resolve(git.stdout.trim());
const install = spawnSync(
  process.execPath,
  [resolve("node_modules/@j178/prek/bin/prek.js"), "install"],
  {
    stdio: "inherit",
    env: {
      ...process.env,
      PREK_HOME: process.env.PREK_HOME || resolve(hooksDirectory, ".prek-cache"),
    },
  },
);
if (install.status !== 0) {
  throw new Error("Failed to install prek hooks", { cause: install.error });
}

// Keep the cache writable when Git runs outside the package manager in Work.
const hookPath = resolve(hooksDirectory, "pre-commit");
const hook = readFileSync(hookPath, "utf8");
const execMarker = 'exec "$PREK" hook-impl';
if (!hook.includes("# File generated by prek:") || !hook.includes(execMarker)) {
  throw new Error("Unexpected prek hook format");
}
writeFileSync(
  hookPath,
  hook.replace(execMarker, 'export PREK_HOME="${PREK_HOME:-$HERE/.prek-cache}"\n\n' + execMarker),
);
